apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: maersk/nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: iscsi-volume
  volumes:
  - name: iscsi-volume
    persistentVolumeClaim:
      claimName: iscsiplugin-pvc
